openapi: 3.0.0
info:
    version: "1.0"
    title: Metaback API
    description: "Documentation de l'api Laravel de IAData"

servers:
    -   url: http://localhost:{port}/api
        variables:
            port:
                enum:
                    - "8000"
                default: "8000"
    - url: https://api-iadata.applis.toulouse-metropole.fr/api/

paths:
    /column/stats:
        post:
            tags:
                - column
            summary: "Statistique sur un jeu de données"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "request/columnStats.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "responses/columnStats.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /liteIndex:
        post:
            tags:
                - index
            summary: "Récupère uniquement les colonnes spécifier"

            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "request/liteIndex.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "responses/liteIndex.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/join:
        post:
            tags:
                - index
            summary: "Permet la jointure et les statistique sur plusieur jeux de données"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "request/indexJoin.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "responses/indexJoin.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/fromPolygon:
        post:
            tags:
                - index
            summary: "Permet le regroupement de point par forme géométrique"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "request/fromPolygon.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "responses/fromPolygon.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

components:
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            in: header
            name: "Authorization"

    schemas:
        Request_Column_Stats:
            $ref: "request/columnStats.yaml"

security:
    -   ApiKeyAuth: []
