openapi: 3.0.0
info:
    version: "1.0"
    title: Metaback API
    description: "Documentation de l'api Laravel de IAData"

servers:
    -   url: http://localhost:{port}/api
        variables:
            port:
                enum:
                    - "8000"
                default: "8000"
    -   url: https://api-iadata.applis.toulouse-metropole.fr/api/

paths:

    /column/stats:
        post:
            tags:
                - column
            summary: "Statistique sur un jeu de données"
            description: "Cette route a pour fonction de faire des statistique sur des colonne du jeu de donnée spécifier."
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "index/post/requests/columnStats.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/post/responses/columnStats.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index:
        get:
            tags:
                - index
            summary: "Retourne les information BDD sur les jeux de données"
            description: "Va chercher directement dans les BDD les information de chaque jeux de donnés"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/get/responses/index.yaml/"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/date/{name}:
        get:
            tags:
                - index
            summary: "Retourne les colonnes date d'un Jeu de données"
            description: "Va retourner sous forme de liste le nom de toute les colonne date d'un jeux de données"
            parameters:
                -   in: path
                    name: name
                    required: true
                    schema:
                        type: string
                        example: horodateurs
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                type: array
                                description: "List des colonnes date trouvé"
                                items:
                                    type: string
                                    example: "@timestamp"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/fields/{name}:
        get:
            tags:
                - index
            summary: "Retourne les info d'un jeu de donné non validé"
            description: "Va retourner le nom de chaque colonne présente dans le jeu de données non validée,
                            ainsi que le nombre de donnée dans la base"
            parameters:
                -   in: path
                    name: name
                    required: true
                    schema:
                        type: string
                        example: cfg_point_mesure
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/get/responses/field.yaml"


                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/accessiblefields/{name}:
        get:
            tags:
                - index
            summary: "Retourne les infos des colonnes accessible d'un jeu de donné"
            description: "Va retourner le nom, le type ainsi que s'il s'agi d'une colonne pivot, pour
                            chaque colonne accessible"
            parameters:
                -   in: path
                    name: name
                    required: true
                    schema:
                        type: string
                        example: horodateurs
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/get/responses/accessibleFields.yaml"


                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /liteIndex:
        post:
            tags:
                - index
            summary: "Récupère uniquement les colonnes spécifier"
            description: "Permet de récupéré uniquement les colonne choisie et donc utile."
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "index/post/requests/liteIndex.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/post/responses/liteIndex.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/last:
        post:
            tags:
                - index
            summary: "Retourne les dernière entré d'un jeux de donnée"
            description: "Va récupéré les dernière entré de chaque occurrence distinguer par
                                une ou plusieurs colonne pivot. Cette route est faite pour fonctionné
                                sur les jeux de donnée marquer 'realtime' en BDD"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "index/post/requests/last.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/post/responses/last.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/join:
        post:
            tags:
                - index
            summary: "Permet la jointure et les statistique sur plusieurs jeux de données"
            description: "Permet de recouper des jeux de donnée afin de les fusionné ou de faire des statistique"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "index/post/requests/indexJoin.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/post/responses/indexJoin.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /index/fromPolygon:
        post:
            tags:
                - index
            summary: "Permet le regroupement de point par forme géométrique"
            description: "Cette route va pouvoir associer les jointure de la route index/join a un
                            regroupement de point par polygone"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "index/post/requests/fromPolygon.yaml"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "index/post/responses/fromPolygon.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /analyse/all:
        get:
            tags:
                - analyse
            summary: "Retourne les info des analyses"
            description: "Retourne toutes les info des analyses auquel l'utlisateur courant a access"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "analyse/get/responses/analyseAll.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /analyse/saved:
        get:
            tags:
                - analyse
            summary: "Retourne les info des analyses sauvegarder"
            description: "Retourne toutes les info des analyses sauvegarder auquel l'utlisateur courant a access"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "analyse/get/responses/analyseSaved.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /datasets/data/validate:
        get:
            tags:
                - datasets
            sumary: "Retourne les info des jeux de données non validé"
            description: "Retourne les colonnes de la table MySql de tout les jeux de données non validée"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "datasets/get/responses/dataValidate.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /datasets/all:
        get:
            tags:
                - datasets
            sumary: "Retourne les info des jeux de données validé"
            description: "Retourne les colonnes de la table MySql de tout les jeux de données validée"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "datasets/get/responses/all.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"

    /datasets/representations/{id}:
        get:
            tags:
                - datasets
            sumary: "Retourne les représentations d'un datasets"
            description: "Retourne les colonnes de représentation MySql d'un jeux de donnée'"
            responses:
                "200":
                    description: "Ok"
                    content:
                        application/json:
                            schema:
                                $ref: "datasets/get/responses/representations.yaml"
                "403":
                    description: "Forbidden"
                "401":
                    description: "Unauthorized"
                "500":
                    description: "Internal serveur Error"


components:
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            in: header
            name: "Authorization"

    schemas:
        Request_Column_Stats:
            $ref: "index/post/requests/columnStats.yaml"

security:
    -   ApiKeyAuth: []
